name: infaim_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - numpy
  - pillow
  - matplotlib
  - pip:
    - timm==0.9.12
    - opencv-python-headless==4.9.0.80